// Copyright (c) 2014-2022 Khronos Group.
//
// SPDX-License-Identifier: CC-BY-4.0

[open,refpage='VkPresentTimesInfoEXT',desc='The earliest time each image should be presented',type='structs']
--

When the <<features-presentAtAbsoluteTime, pname:presentAtAbsoluteTime>> or
<<features-presentAtRelativeTime, pname:presentAtRelativeTime>> feature is
enabled, additional fields can: be specified that allow an application to
specify the earliest time that an image should be displayed.
This allows an application to avoid stutter that is caused by an image being
displayed earlier than planned.
Such stuttering can occur with both fixed and variable-refresh-rate
displays, because stuttering occurs when the geometry is not correctly
positioned for when the image is displayed.
An application can: instruct the presentation engine that an image should
not be displayed earlier than a specified time by including the
sname:VkPresentTimesInfoEXT structure in the pname:pNext chain of the
sname:VkPresentInfoKHR structure.

The sname:VkPresentTimesInfoEXT structure is defined as:

include::{generated}/api/structs/VkPresentTimesInfoEXT.adoc[]

  * pname:sType is the type of this structure.
  * pname:pNext is `NULL` or a pointer to a structure extending this
    structure.
  * pname:swapchainCount is the number of swapchains being presented to by
    this command.
  * pname:pTimes is `NULL` or a pointer to an array of
    sname:VkPresentTimeEXT elements with pname:swapchainCount entries.
    If not `NULL`, each element of pname:pTimes contains the earliest time
    to present the image corresponding to the entry in the
    sname:VkPresentInfoKHR::pname:pImageIndices array.

The semantics of a specified present time only apply to the following present
modes:

  * ename:VK_PRESENT_MODE_FIFO_KHR.
    Tearing cannot be observed.
    The first queued image is dequeued and presented if
    both: 1) its associated wait semaphore(s) have signaled, and 2)
    its target present time is less-than or equal-to the current time.
  * ename:VK_PRESENT_MODE_FIFO_RELAXED_KHR.
    For images that are presented in time to be displayed at the next
    vertical blanking period, the semantics are identical as for
    ename:VK_PRESENT_MODE_FIFO_RELAXED_KHR.
    For images that are presented late, and are displayed after the start of
    the vertical blanking period (i.e. with tearing), the values of
    sname:VkPastPresentationTimingEXT may: be treated as if the image was
    displayed at the start of the vertical blanking period, or may: be
    treated the same as for ename:VK_PRESENT_MODE_IMMEDIATE_KHR.

.Valid Usage
****
  * pname:swapchainCount must: be the same value as
    sname:VkPresentInfoKHR::pname:swapchainCount, where
    sname:VkPresentInfoKHR is in the pname:pNext chain of this
    sname:VkPresentTimesInfoEXT structure.
  * For each member of sname:VkPresentInfoKHR::pname:pSwapchains, the present
    mode must: be ename:VK_PRESENT_MODE_FIFO_KHR or
    ename:VK_PRESENT_MODE_FIFO_RELAXED_KHR.
****

include::{generated}/validity/structs/VkPresentTimesInfoEXT.adoc[]
--

[open,refpage='VkPresentTimeEXT',desc='Specifying when an image should be presented',type='structs']
--

The sname:VkPresentTimeEXT union is defined as:

include::{generated}/api/structs/VkPresentTimeEXT.adoc[]

  * pname:absolutePresentTime is a slink:VkAbsolutePresentTimeEXT structure.
  * pname:relativePresentTime is a slink:VkRelativePresentTimeEXT structure.

include::{generated}/validity/structs/VkPresentTimeEXT.adoc[]
--

[open,refpage='VkAbsolutePresentTimeEXT',desc='Specifying the earliest time an image should be presented',type='structs']
--

The sname:VkAbsolutePresentTimeEXT structure is defined as:

include::{generated}/api/structs/VkAbsolutePresentTimeEXT.adoc[]

  * pname:targetPresentTime, if non-zero, specifies the earliest time the
    application wants the image to be displayed to the user.
    pname:targetPresentTime is a time in nanoseconds, according to the
    time-domain being used.
    A value of zero specifies that the presentation engine may: display the
    image at any time.
  * pname:presentSlop is the period of time in nanoseconds before
    pname:targetPresentTime that the presentation engine may: display
    the image.

If pname:targetPresentTime is non-zero, the presentation engine should:
not display the image to the user at a time earlier than
(pname:targetPresentTime - pname:presentSlop).

Providing a pname:presentSlop enables the application to indicate to the
presentation engine to display the image within this period if a vertical
blanking period occurs on FRR displays.

[NOTE]
.Note
====
The pname:presentSlop is used to avoid unintentionally missing a vertical
blanking period on FRR displays due to rounding errors or drift between
clocks.
A suggested value for pname:presentSlop is half the _Refresh Rate_.
====

include::{generated}/validity/structs/VkAbsolutePresentTimeEXT.adoc[]

--

[open,refpage='VkRelativePresentTimeEXT',desc='Specifying the minimum duration an image should be presented',type='structs']
--

The sname:VkRelativePresentTimeEXT structure is defined as:

include::{generated}/api/structs/VkRelativePresentTimeEXT.adoc[]

  * pname:minPresentDuration, if non-zero, specifies the minimum duration
    in nanoseconds the application wants the image to be displayed to the
    user.
    A value of zero specifies that the presentation engine may: display the
    image for any duration.
  * pname:presentSlop is the period of time in nanoseconds before
    pname:minPresentDuration elapses that the presentation engine may:
    display the image.

If pname:minPresentDuration is non-zero, the presentation engine should:
display the image to the user for a minimum duration of
(pname:minPresentDuration - pname:presentSlop) nanoseconds.

Providing a pname:presentSlop enables the application to indicate to the
presentation engine to display the image within this period if a vertical
blanking period occurs on FRR displays.

[NOTE]
.Note
====
The pname:presentSlop is used to avoid unintentionally missing a vertical
blanking period on FRR displays due to rounding errors or drift between
clocks.
A suggested value for pname:presentSlop is half the _Refresh Cycle Duration_.
====

include::{generated}/validity/structs/VkRelativePresentTimeEXT.adoc[]

--
